### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by joeybaker** [mdibaiee/hapi-sequelize-crud#19]
I've run into enough edge cases in the code that it would be really nice to have tests to give assurance that the right things are happening. Though I'm a tape/tap fan usually, I've been wanting to give Ava or Jest a try. 

@mdibaiee what do you think of adding tests and do you care about the framework?

**Comment by mdibaiee** [comment]
Sure thing tests are great! I have no preference for any test framework here, please use the one you think is appropriate.

Thanks!

**Comment by mdibaiee** [comment]
fixed in #22.
