### ISSUE TITLE
Support custom ID fields

### ISSUE THREAD

**Issue by casalot** [mdibaiee/hapi-sequelize-crud#9]
@mdibaiee, I'm seeing some strange behaviour with the auto route creation.

Here's an example of 2 of my entity models:
`Position`

``` javascript
module.exports = function(sequelize, DataTypes) {
  var Position = sequelize.define('Position', {
    positionId: {
      type: DataTypes.INTEGER(11),
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
    title: {
      type: DataTypes.STRING,
      allowNull: false
    },
    createdAt: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: 'CURRENT_TIMESTAMP'
    },
    updatedAt: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: 'CURRENT_TIMESTAMP'
    }
  }, {
    tableName: 'Position'
  });
  return Position;
};
```

`Question`

``` javascript
module.exports = function(sequelize, DataTypes) {
  var Question = sequelize.define('Question', {
    questionId: {
      type: DataTypes.INTEGER(11),
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
    questionnaireSectionId: {
      type: DataTypes.INTEGER(11),
      allowNull: false,
      defaultValue: '0',
      references: {
        model: 'QuestionnaireSection',
        key: 'questionnaireSectionId'
      }
    },
    title: {
      type: DataTypes.STRING,
      allowNull: false
    },
    description: {
      type: DataTypes.STRING,
      allowNull: true
    },
    weight: {
      type: DataTypes.INTEGER(4),
      allowNull: false,
      defaultValue: '1'
    },
    sortOrder: {
      type: DataTypes.INTEGER(11),
      allowNull: false,
      defaultValue: '0'
    },
    createdAt: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: 'CURRENT_TIMESTAMP'
    },
    updatedAt: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: 'CURRENT_TIMESTAMP'
    }
  }, {
    tableName: 'Question'
  });
  return Question;
};
```

And, the created routes:
`Position`

```
POST   /api/seq/position
GET    /api/seq/position/{id?}
DELETE /api/seq/position/{id?}
PUT    /api/seq/position/{id}
DELETE /api/seq/positions
GET    /api/seq/positions
GET    /api/seq/positions/{scope}
DELETE /api/seq/positions/{scope}
```

`Question`

```
GET    /api/seq/questions
DELETE /api/seq/questions
DELETE /api/seq/questions/{scope}
GET    /api/seq/questions/{scope}
```

**Comment by mdibaiee** [comment]
This is indeed weird, hmm...

One thing is, we use `{ id: request.query.id }` for finding by `id`, and you are using custom fields, `questionId` and `positionId`.

But you say the Position model's id route works! Now that's inconsistency. Do you get any errors/warnings?

Let me see if I can reproduce your problem.

**Comment by casalot** [comment]
`/position/1`and `/question/1` throws 500.
`/positions/1` and `/questions/1` throws 400, with message "**child \"scope\" fails because [\"scope\" must be one of []]**".

`/poisitions` and `/questions` (without id's) works 100%.

**Comment by mdibaiee** [comment]
Okay, so it's not inconsistency, is it? You get the same routes for both models, if that's the case, your problem is with `id`s.

You have `positions/{scope}`, not `positions/{id}`, instead there is `position/{id}` (which doesn't work in your case.

If I'm correct, the problem is with custom id fields.

**Comment by casalot** [comment]
I think the custom id is one of the issues. I don't understand why the `position` entity has 8 routes defined, and the `question` just 4? Or, are these two questions/issues related?

**Comment by mdibaiee** [comment]
@casalot: Maybe you have relations/associations defined for your `Position` model?

**Comment by casalot** [comment]
Nope. Neither `Position` nor `Question` has any relations defined.

**Comment by mdibaiee** [comment]
Umm, I'm not sure about that. But I think we can address the id issue here, and if you encounter any problem with the routes, we'll get to that later. What do you say?

**Comment by casalot** [comment]
Cool. Should I rename the custom id's to `id`? Or, is there a why to alias it?

**Comment by mdibaiee** [comment]
I think we should allow custom id fields, I'm seeing if there is a way to automatically detect ID fields (using PRIMARY KEYs, INDEXes, etc.), or we should ask the programmer to explicitly set the custom field's name.

**Comment by casalot** [comment]
I have set `primaryKey: true` on both entities. Didn't make a difference.

Changing the id from `positionId` to `id` on the database table, now gets results back for `/position/1`.

**Comment by mdibaiee** [comment]
Okay it seems there is a way to automatically use the primary key set by programmer, I'm going to patch it right now. :+1:

**Comment by mdibaiee** [comment]
Published to npm `hapi-sequelize-crud@2.4.0`, see if it works for you.

**Comment by casalot** [comment]
Working perfect now!

**Comment by mdibaiee** [comment]
Great! :+1:
